version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
#    volumes:
#      - :
#    depends_on:
#      - redis
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "8880:80"
      - "8443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=asd@qwe.pl
      - PGADMIN_DEFAULT_PASSWORD=password